# SCRATCH PAPER! NOT PART OF THE PROJECT

This file is a general utility file for debuggign and testing code. 

I use it to test specific sections of the script that I write. 

It is nto meant to be read and shouldn't be looked at as part of the project. 

At the end of the day, I just like testing things in notebooks.

In [2]:
import pandas as pd
import fred_calls.duckdb_utils as ddu

In [3]:
pd.read_csv("/home/connor/projects/economics_project/fred_data_test.csv")

           date  value                processed_at
0    1948-01-01    3.4  2026-03-10 19:11:17.205238
1    1948-02-01    3.8  2026-03-10 19:11:17.205238
2    1948-03-01    4.0  2026-03-10 19:11:17.205238
3    1948-04-01    3.9  2026-03-10 19:11:17.205238
4    1948-05-01    3.5  2026-03-10 19:11:17.205238
..          ...    ...                         ...
933  2025-10-01    NaN  2026-03-10 19:11:17.205238
934  2025-11-01    4.5  2026-03-10 19:11:17.205238
935  2025-12-01    4.4  2026-03-10 19:11:17.205238
936  2026-01-01    4.3  2026-03-10 19:11:17.205238
937  2026-02-01    4.4  2026-03-10 19:11:17.205238

[938 rows x 3 columns]

In [4]:
duck_client = ddu.DuckClient("/home/connor/projects/economics_project/fred_data/economics.db")
print(duck_client.query_db("SELECT* FROM raw.recession_indicators"))

           date  value               processed_at
0    1855-09-01    0.0 2026-03-18 12:41:19.242199
1    1856-10-01    0.0 2026-03-18 12:41:19.242199
2    1857-12-01    1.0 2026-03-18 12:41:19.242199
3    1859-11-01    0.0 2026-03-18 12:41:19.242199
4    1860-05-01    0.0 2026-03-18 12:41:19.242199
...         ...    ...                        ...
2050 2024-12-01    0.0 2026-03-18 12:41:19.242199
2051 2025-03-01    0.0 2026-03-18 12:41:19.242199
2052 2025-05-01    0.0 2026-03-18 12:41:19.242199
2053 2025-08-01    0.0 2026-03-18 12:41:19.242199
2054 2026-01-01    0.0 2026-03-18 12:41:19.242199

[2055 rows x 3 columns]

In [15]:
all_fred = duck_client.query_db("SELECT * FROM stg_fred_date_based_data WHERE indicator_name = 'recession_indicators'")
all_fred

            indicator_name fred_series_id       date  value
0     recession_indicators          USREC 1855-09-01    0.0
1     recession_indicators          USREC 1856-10-01    0.0
2     recession_indicators          USREC 1857-12-01    1.0
3     recession_indicators          USREC 1859-11-01    0.0
4     recession_indicators          USREC 1860-05-01    0.0
...                    ...            ...        ...    ...
2050  recession_indicators          USREC 2024-12-01    0.0
2051  recession_indicators          USREC 2025-03-01    0.0
2052  recession_indicators          USREC 2025-05-01    0.0
2053  recession_indicators          USREC 2025-08-01    0.0
2054  recession_indicators          USREC 2026-01-01    0.0

[2055 rows x 4 columns]